cn:
  title: "车辆管理系统"
  home: "首页"
  rental: "租赁"
  notice: "公告"
  member: "会员"
  about: "关于我们"
  dashboard: "仪表盘"
  vehicles: "车辆管理"
  vehicle_list: "车辆列表"
  vehicle_detail: "车辆详情"
  vehicle_edit: "编辑车辆"
  vehicle_files: "车辆文件"
  vehicle_logs: "车辆日志"
  admin: "管理员"
  admin_users: "用户管理"
  admin_field_permissions: "字段权限"
  language_switch: "语言切换"
  lang_cn: "中文"
  lang_jp: "日本語"
  logout: "退出登录"
  login: "登录"
  register: "注册"
jp:
  title: "車両管理システム"
  home: "ホーム"
  rental: "レンタル"
  notice: "お知らせ"
  member: "会員"
  about: "私たちについて"
  dashboard: "ダッシュボード"
  vehicles: "車両管理"
  vehicle_list: "車両リスト"
  vehicle_detail: "車両詳細"
  vehicle_edit: "車両編集"
  vehicle_files: "車両ファイル"
  vehicle_logs: "車両ログ"
  admin: "管理者"
  admin_users: "ユーザー管理"
  admin_field_permissions: "フィールド権限"
  language_switch: "言語切替"
  lang_cn: "中国語"
  lang_jp: "日本語"
  logout: "ログアウト"
  login: "ログイン"
  register: "登録"